### ISSUE TITLE
Text not displaying when entered

### ISSUE THREAD

**Issue by ghost** [hughbarney/atto#1]
Got atto up and running but when I entered text into the scratch buffer nothing would show up.
C-v and other coords did move the cursor but no text would show up when I entered it.
I thought that it might have been my font (dejavu mono) but the font was showing up fine in the modelines. 
Then I thought it may have been my terminal colorscheme so I made all of them contrasting, and that too did not change anything.
Any ideas?

![2015-12-14-010502_1366x768_scrot](https://cloud.githubusercontent.com/assets/13292966/11773988/b7689914-a1fe-11e5-8132-5ce7de99fe6e.png)

**Comment by hughbarney** [comment]
Assume you built it ok without errors ?
Assuming what flavour of linux are you using ?  (uname -a)

From the screenshot I can see that the scratch buffer's modified flag has been set.  That is the \* at the beginning of the modeline.  It looks like everything is working but you just cant see it. So this to me looks like some sort of black on black problem in the main screen area.  The modeline is reversed.

Can you try in another type of terminal ?  So if you are using xterm, switch to the terminal programme and vice versa,  This will establish it is a problem with the terminal setup.   The code does not select colours or medel with the colour scheme.  Apart from the modeline which is just to reverse the foreground and background colours.

Try this little programme below.  

#include <ncurses.h>
int main()
{  
    initscr();          /\* Start curses mode          _/
    addstr("Hello World !!!");  /_ Print Hello World          _/
    refresh();          /_ Print it on to the real screen _/
    getch();            /_ Wait for user input _/
    endwin();           /_ End curses mode        */
    return 0;
}

gcc try.c -lncurses
chmod +x a.out
./a.out
Hit return after you have observed the display.

If you dont see Hello World!!! printed then I suspect the problem is something to do with your terminal setup.

Let me know how you get on.

**Comment by teddy-ma** [comment]
I use OS X EI Capitan and have the same issue.
I use both iterm2 and OS X default terminal.
I try to use your little programme and it looks that the terminal clears buffer.

![untitled](https://cloud.githubusercontent.com/assets/788486/11806552/d7a06b0c-a34e-11e5-9ef1-64bb23138426.gif)

**Comment by ghost** [comment]
![2015-12-15-063528_1366x768_scrot](https://cloud.githubusercontent.com/assets/13292966/11809608/10802ca4-a2f6-11e5-874d-dd850bd14011.png)

I tried a couple terminals and its all the same, bottom corner is output of uname -a and the little program that you gave out.

**Comment by hughbarney** [comment]
Both. I am thinking this is maybe a problem (or a difference) with the ncurses library being used.

Try the following to see what libraries are being used.  I've got libncurses.so.5.

$ strings atto|grep lib
/lib64/ld-linux-x86-64.so.2
libncurses.so.5
libtinfo.so.5
libc.so.6
__libc_start_main
__libc_csu_fini
__libc_start_main@@GLIBC_2.2.5
__libc_csu_init
$ 


@teddy-ma - The test programme should pause until you hit a key.   If not then the version of ncurses in use is not working as I would expect.

**Comment by hughbarney** [comment]
Guys - reproduced the issue and fixed the bug in Atto 1.4.3.  I introduced this in Atto 1.4 when I added windows support.  The bug was not clearing correctly from the last character displayed.  Instead I was clearing from the last line displayed.  So with the buggy version you will see what you have typed after you enter a carriage return at the end of the line.

Please pull the latest code and retry.
Thanks
Hugh

**Comment by teddy-ma** [comment]
It works now :+1:

**Comment by ghost** [comment]
Everything works now!
