### ISSUE TITLE
opening ~/file does not work

### ISSUE THREAD

**Issue by rapha8l** [hughbarney/atto#10]
Hi,

Inside of atto, I tried to load a ~/file and it says "new file" and is empty.
Though the file exists and is not empty
Thanks

**Comment by hughbarney** [comment]
Hi There,

When a file fails to open Atto will create an empty file.

I am assuming you are using the latest version of Atto on a Unix based
system.

There are a couple of things you can try to confirm that you are loading
the file you are expecting.

1) start at the unix shell command line and type:

    $ atto filename.txt

   Does the file load as you would expect ?

2) When you do C-x C-f you can use the TAB key to complete the filename.

  So Enter ~/fil  [just a first few letters of the filename] then hit TAB
to see if the filename comes up.

I guess it is possible you have a space in the filename.  This often causes
issues on a unix based file system.

Hope this helps
Hugh

**Comment by rapha8l** [comment]
Hi,

Thanks for your reply.
1) works
2) works with tab but not if I type all the path
Example : I tried to load my .zshrc which has no special character, with CxCf with tab, it's ok, if I CxCf and write the full path by hand ~/.zshrc, I get "new file" and if I try to save it, I get "Not a portable POSIX file name."

My system is a Debian GNU/Linux

**Comment by hughbarney** [comment]
hmm - strange one this,

I tested with my ~/.emacs file and it works fine.  I am on Ubuntu.

It sounds like there is something odd or strange with the filename.
The auto-completion (command line or in Atto C-x C-f) will skip over
anything hidden.
The problem is only when you type the name.

Try using the follow bash script
$ bash
$ for f in `ls .z*`; do echo ":$f:"; done
:.zile:
:.zshrc:

This should list the filenames with colons around the name.  See if there
is something else just before the expected start or end of the filename.


The other thing to try to see what the real filename is would be to send
the output to a file and look at it with the octal dump programme.

$ for f in `ls .z*`; do echo ":$f:"; done >> tt
$
$ od -c tt
0000000   :   .   z   i   l   e   :  \n   :   .   z   s   h   r   c   :
0000020  \n
0000021
$

This should show if there is some additional character in the file.

Otherwise could you send me an example copy of a file that behaves like
this.

Thanks
Hugh

**Comment by rapha8l** [comment]
Hi,

I tried also with my ~/.emacs and get the same behaviour.
Same for .jedrc, .zile, .Xresources or .tmux.conf
the first scripts gives : 
:.zshrc:
The second : 

0000060   t   :  \n   :   .   z   s   h   r   c   :  \n   :   .   z   s

thanks

**Comment by hughbarney** [comment]
Ok.  Looking at the code I can see a way to test this further.

Start Atto
C-xC-f to open a file that does not exist.
. Eg fff
Now C-xC-i to insert a file
Type your filename in

You should see some message on the msg line if something fails.

Let me know what happens.

This has highlighted a problem with the potential for a message to be lost
during a file open.

Hugh

**Comment by rapha8l** [comment]
Hi,

I tried (though I did Cx i and not CX Ci)
The message is : 
Failed to find file "~/.zshrc".

**Comment by rapha8l** [comment]
also I tested using bash instead of zsh (not sure it could have any relation) and get the same error
thanks

**Comment by hughbarney** [comment]
I have reproduced it now.

The code is not expanding ~/.emacs to /home/hugh/.emacs when entered
without filename completion.

Will take a look at this:
http://www.dreamincode.net/forums/topic/197372-how-to-expand-a-path-linux/

Need to find a coding efficient way to do this.
A work round is to enter ~/.emacs and then hit TAB to expand it to the
fullpath name.
Then hit enter.

Good spot.
Hugh

**Comment by rapha8l** [comment]
Good luck !
I'll use tab instead, but habits are hard to change

**Comment by hughbarney** [comment]
I have fixed the issue.  If you hit ENTER the code will detect that the file name has a ~ in it and force a filename completion as if you had pressed TAB instead.  See what you think. This is is a bit of a cheat solution, not sure if it will feel right or not BUT it has the advantage of only being 2 lines of code to fix. See what you think.

**Comment by hughbarney** [comment]
One final comment is that filename completion is really nice.  Do C-x C-f, at the prompt type the first part of the filename that you want (~/.em might be enough for a .emacs file) and hit TAB, Atto will then find the file and expand to its full name. If there is more that one matching file then hitting TAB again will cycle through the files. Hit ENTER when you reach the one that you want.

**Comment by rapha8l** [comment]
Hi, It takes on enter more than usual but it works :) 
I use tab in emacs, I'll use it in atto !
Thanks for the fix
